export { default as AlipayPay  } from './alipay'
// export { default as WeappPay } from './weapp'
export { default as WePay } from './we'
export { default as WeH5Pay } from './we-h5'
export { default as PointDepositPay } from './point-deposit'
