export { default as HeaderHome } from './header-home'
export { default as WgtSlider } from './slider'
export { default as WgtLimittimeSlider } from './limittime-slider'
export { default as WgtNavigation } from './navigation'
export { default as WgtCoupon } from './coupon'
export { default as WgtGoodsScroll } from './goods-scroll'
export { default as WgtGoodsGrid } from './goods-grid'
export { default as WgtShowcase } from './showcase'
export { default as WgtSearchHome } from './search-home'
export { default as WgtFilm } from './film'
export { default as WgtWriting } from './writing'
export { default as WgtHeading } from './heading'
export { default as WgtGoods } from './goods'
export { default as WgtGoodsFaverite } from './goods-faverite'
export { default as WgtImgHotZone } from './imghot-zone'
export { default as WgtMarquees } from './marquees'
export { default as FeautreSelect } from './feautre-select'
export { default as HotArea } from './hot-area'
export { default as WgtLimitKill } from './own-limit-kill'

export default {}
